name: Terraform Deploy

on:
  push:
    branches:
      - main
    paths:
      - "terraform/**"

jobs:
  terraform:
    name: Apply Terraform Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        env:
          TF_VAR_example: ${{ secrets.MY_TF_VAR }}
        run: terraform -chdir=terraform apply -auto-approve
