name: Deploy Auth Lambda

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd auth
          pip install -r requirements.txt -t package/

      - name: Zip Lambda function
        run: |
          cd auth
          cp auth_function.py package/
          cd package
          zip -r ../auth_function.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # ajuste conforme necessário

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name auth-service \
            --zip-file fileb://auth/auth_function.zip
